ARG BASE_IMAGE=autopilot-ws-base
FROM ${BASE_IMAGE}

COPY requirements.txt /requirements.txt
RUN /home/node/venv/bin/pip install -r /requirements.txt

COPY app/ /app/

ARG DEBUG=0
ENV DEBUG=${DEBUG}

EXPOSE 8501
RUN chmod +x /app/run.sh

